export const tabsData = [
  { name: "Mobile" },
  { name: "DTH" },
  { name: "Electricity" },
  { name: "Gas Cylinder" },
  { name: "Redeem Code" },
  { name: "Piped Gas" },
  { name: "Water" },
  { name: "Fast Tag" },
  { name: "Postpaid" },
  { name: "Lone Repayment" },
  { name: "Landline" },
  { name: "Insurance" },
  { name: "Cable TV" },
  { name: "Broadband" },
  { name: "Credit Card" },
  { name: "Muncipal Tax" },
  { name: "Housing Society" },
  { name: "Clubs & Associations" },
  { name: "Education Fees" },
  { name: "Hospital & Pathology" },
  { name: "Subscription" },
];
